<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="arm">

	<xacro:macro name="arm" params="prefix reflect flip lower_limit upper_limit *joint_pose">
		
		<link name="${prefix}_arm">
			<visual>
				<origin rpy="${flip*M_PI} ${0} ${0}" xyz="-${actuator_z_size/1.5} ${reflect*2.5*lower_leg_radius}  ${reflect*2*lower_leg_radius}"/>
				<geometry>
					<mesh filename="package://igor/meshes/lowerLeg.STL" scale="0.001 0.001 0.001"/>
		      		</geometry>
		      		<material name="white"/>
		    	</visual>      

			<collision>
				<origin rpy="0.0 ${M_PI/2} 0.0" xyz="${lower_leg_length/2} 0.0 ${0}"/>
				<geometry>
					<cylinder radius="${lower_leg_radius}" length="${lower_leg_length}" /> <!-- Actual dimensions --> 
		      		</geometry>

		    	</collision>

	    		<inertial>
				<origin rpy="0.0 ${M_PI/2} 0.0" xyz="${lower_leg_length/2} 0.0 ${0}"/>
	      			<mass value="0.2"/>
	      			<inertia ixx="0.001521" ixy="0.00" ixz="0.00" iyy="0.001521" iyz="0.000" izz="4.2E-05"/>
	    		</inertial>
   
	    	</link>

		<joint name="${prefix}_arm_joint" type="revolute">
			<xacro:insert_block name="joint_pose"/>
			<parent link="${prefix}_armActuator"/>
			<child  link="${prefix}_arm"/>
			<limit effort="15" lower="${lower_limit}" upper="${upper_limit}" velocity="15"/>
			<axis xyz="0 0 1"/>
			<dynamics damping="0.1"/>
		</joint>

		<transmission name="${prefix}_arm_trans">
	      		<type>transmission_interface/SimpleTransmission</type>
	      		<actuator name="${prefix}_arm_motor">
				<mechanicalReduction>1</mechanicalReduction>
	      		</actuator>
	      		<joint name="${prefix}_arm_joint">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	      		</joint>
	    	</transmission>

	    	<gazebo reference="${prefix}_arm">
	      		<mu1 value="1.0"/>
	      		<mu2 value="1.0"/>
	      		<kp value="10000.0" />
	      		<kd value="10000.0" />
	      		<material>Gazebo/Grey</material>
	    	</gazebo>





	</xacro:macro>


</robot>
