<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="lowerLeg">

	<xacro:macro name="lowerLeg" params="prefix reflect flip *joint_pose">
		
		<link name="${prefix}_lowerleg">
			<visual>
				<origin rpy="${M_PI/2} ${M_PI/2} ${flip*M_PI}" xyz="${reflect*-2.5*lower_leg_radius} ${reflect*2*lower_leg_radius} ${actuator_z_size/1.5}"/>
				<geometry>
					<mesh filename="package://igor/meshes/lowerLeg.STL" scale="0.001 0.001 0.001"/>
					<!--cylinder radius="0.03175" length="0.3" /-->
		      		</geometry>
		      		<material name="white"/>
		    	</visual>      

			<collision>
				<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 -${lower_leg_length/2}"/>
				<geometry>
					<cylinder radius="${lower_leg_radius}" length="${lower_leg_length}" /> <!-- Actual dimensions --> 
		      		</geometry>

		    	</collision>

	    		<inertial>
				<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 -${lower_leg_length/2}"/>
	      			<mass value="0.2"/>
	      			<inertia ixx="0.001521" ixy="0.00" ixz="0.00" iyy="0.001521" iyz="0.000" izz="4.2E-05"/>
	    		</inertial>
   
	    	</link>

		<joint name="${prefix}_kfe_joint" type="revolute">
			<xacro:insert_block name="joint_pose"/>
			<parent link="${prefix}_kneeActuator"/>
			<child  link="${prefix}_lowerleg"/>
			<limit effort="15" lower="${-0.65}" upper="${-0.65}" velocity="10"/>
			<axis xyz="0 1 0"/>
			<dynamics damping="0.1"/>
		</joint>

		<transmission name="${prefix}_kfe_trans">
	      		<type>transmission_interface/SimpleTransmission</type>
	      		<actuator name="${prefix}_kfe_motor">
				<!--hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface-->
				<mechanicalReduction>1</mechanicalReduction>
	      		</actuator>
	      		<joint name="${prefix}_kfe_joint">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	      		</joint>
	    	</transmission>

	    	<gazebo reference="${prefix}_lowerleg">
	      		<mu1 value="1.0"/>
	      		<mu2 value="1.0"/>
	      		<kp value="10000.0" />
	      		<kd value="10000.0" />
	      		<material>Gazebo/Grey</material>
	    	</gazebo>



		
			<!-- IMU Sensor -->


		<!-- imu_link for getting data in imu frame -->
	    	<!--link name="${prefix}_lowerLeg_imu_link"/>

		<joint name="${prefix}_lowerLeg_imu_link_to_${prefix}_lowerleg" type="fixed">
			<origin xyz="0 0 -${lower_leg_length/2}" rpy="0 0 0" />
			<parent link="${prefix}_lowerleg" />
			<child link="${prefix}_lowerLeg_imu_link" />
		</joint>

		<gazebo reference="${prefix}_lowerleg">
		    <gravity>true</gravity>
		    <sensor name="{prefix}_lowerLeg_imu" type="imu">
		      <always_on>true</always_on>
		      <visualize>true</visualize>
		      <!topic>__default_topic__</topic>
		      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
			<robotNamespace>/igor</robotNamespace>
			<topicName>${prefix}_lowerLeg_imu/data</topicName>
			<bodyName>${prefix}_lowerleg</bodyName>
			<updateRateHZ>500.0</updateRateHZ>
			<gaussianNoise>0.0</gaussianNoise>
			<xyzOffset>0 0 0</xyzOffset>
			<rpyOffset>0 0 0</rpyOffset>
			<frameName>${prefix}_lowerLeg_imu_link</frameName>
		      </plugin>
		      <pose>0 0 0 0 0 0</pose>
		    </sensor>
		</gazebo-->




	</xacro:macro>


</robot>
